#!/bin/bash

# Enable JupyterLab widgets extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

# Install TOC extension
jupyter labextension install @jupyterlab/toc --no-build

# Configure all diff/merge drivers and tools for nbdime
nbdime config-git --enable --global

# Build and clean up
jupyter lab build
npm cache clean --force
jupyter lab clean
jupyter notebook --generate-config
rm -rf $CONDA_DIR/share/jupyter/lab/staging
rm -rf /home/$USERNAME/.cache/yarn
rm -rf /home/$USERNAME/.node-gyp